EXPLAIN ANALYZE SELECT * from photos WHERE listing_id=4873561;
EXPLAIN ANALYZE SELECT * from photos WHERE listing_id=9873561;
EXPLAIN ANALYZE SELECT * from photos WHERE listing_id=44;

EXPLAIN ANALYZE INSERT INTO photos 
EXPLAIN ANALYZE INSERT INTO photos 
EXPLAIN ANALYZE INSERT INTO photos 


