const express = require('express');
const path = require('path');
const db = require('./../db/index.js');
const moreFake = require('../db/moreFakeData');

const app = express();
const PORT = 4000;

app.use(express.static(path.join(__dirname, '..', 'public')));

app.get('/photos', (req, res) => {
  const listingId = req.query.listingid;
  db.getPhotos(listingId, (err, photos) => {
    if (err) {
      res.status(500).send(err);
    } else {
      res.status(200).send(photos);
    }
  });
});

app.post('/photos', (req, res) => {
  const entry = moreFake.makeFakeEntry();

  // would ideally require information from the client to post a photo. But, for now, POST
  // data is randomly generated by a helper function to test the route.
  // const { entry } = req.query.entry;
  db.addPhoto(entry, (err) => {
    if (err) {
      res.status(500).send();
    }
    res.status(200).send();
  });
});

app.delete('/photos', (req, res) => {
  const { id } = req.query;
  db.deletePhoto(id, (err) => {
    if (err) {
      res.status(500).send();
    }
    res.status(200).send();
  });
});

// for now, takes an id that must be supplied from the client and generates
// fake data that is inserted and updates the db at the location of the id
// needs future refactoring in order to properly update information from the client. But,
// I will, at this time, ignore this front-end functionality and move forward.

app.put('/photos', (req, res) => {
  const { id } = req.query;
  const entry = moreFake.makeFakeEntry();
  db.updatePhoto(id, entry, (err) => {
    if (err) {
      res.status(500).send();
    }
    res.status(200).send();
  });
});

app.listen(PORT, () => {
  console.log(`Server is now listening on port ${PORT}`);
});
